### PR TITLE
✌ Streams are now working

### PR DESCRIPTION
**Pull request by kushpatel10**
### **Streams Are Working From Now on** ✔

- Added Consumet API to get links for streaming .
- Changed the player to stream only m3u8 file extensions .
- Added CORS proxy to the project .

### CODE REVIEW

**Comment by jeydinpham** [comment]
Woah...

**Comment by kushpatel10** [comment]
Should I change the html5 player to plyr?

**Comment by jeydinpham** [comment]
Yes plyr is amazing

**Comment by kushpatel10** [comment]
I have added the plyr but UI sucks 😭& it was pain in the ass the add quality selector button.

**Comment by kushpatel10** [comment]
### **Updated**

- Added Plyr Html5 player
- Removed Video.js
- Added Quality selector button

**Contact Me (Discord)** - Ghoul#0995
**Demo**- https://anime-hub.kekpet.repl.co/

**Comment by kushpatel10** [comment]
accept pull req when 😭😭

**Comment by jeydinpham** [comment]
Author's last few commits were months ago in private repositories, I don't think they use this account anymore or maybe they don't develop anymore.

**Pull request merged**
